# vim:sw=2:ts=2
name: build
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  check_debian:
    runs-on: ubuntu-latest
    outputs:
      should-update: ${{ steps.check.outputs.should-update }}
    steps:
      -
        id: check
        name: Check new release
        uses: vilgotf/container-update-action@main
        with:
          baseimage: library/python:3.8-slim
          image: vilgotf/red-discordbot:debian
          pypi: red-discordbot
  check_alpine:
    runs-on: ubuntu-latest
    outputs:
      should-update: ${{ steps.check.outputs.should-update }}
    steps:
      -
        id: check
        name: Check new release
        uses: vilgotf/container-update-action@main
        with:
          baseimage: library/python:3.8-alpine
          image: vilgotf/red-discordbot
          pypi: red-discordbot
  alpine:
    needs: check_alpine
    if: needs.check_alpine.outputs.should-update == 'true'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        tags: [minimal, audio, latest, full]
        platforms: [amd64, arm/v6, arm/v7, arm64]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./Containerfile.alpine
          target: ${{ matrix.tags }}
          platforms: linux/${{ matrix.platforms }}
          push: true
          tags: vilgotf/red-discordbot:${{ matrix.tags }}
  debian:
    needs: check_debian
    if: needs.check_debian.outputs.should-update == 'true'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        tags: [audio, full]
        platforms: [amd64, arm/v6, arm/v7, arm64]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./Containerfile.debian
          target: ${{ matrix.tags }}
          platforms: linux/${{ matrix.platforms }}
          push: true
          tags: vilgotf/red-discordbot:${{ matrix.tags }}-debian
      -
        name: Build and push Debian
        uses: docker/build-push-action@v2
        with:
          file: ./Containerfile.debian
          target: audio
          platforms: linux/${{ matrix.platforms }}
          push: true
          tags: vilgotf/red-discordbot:debian
