name: build
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push minimal
        uses: docker/build-push-action@v2
        with:
          file: ./Containerfile.alpine
          target: minimal
          push: true
          tags: vilgotf/red-discordbot:minimal
      -
        name: Build and push audio
        uses: docker/build-push-action@v2
        with:
          file: ./Containerfile.alpine
          target: audio
          push: true
          tags: |
            vilgotf/red-discordbot:latest
            vilgotf/red-discordbot:audio
      -
        name: Build and push audio-debian
        uses: docker/build-push-action@v2
        with:
          file: ./Containerfile.debian
          push: true
          tags: vilgotf/red-discordbot:audio-debian
