# vim:sw=2:ts=2
name: check, build and deploy Debian
on:
  #schedule:
  #- cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check_debian:
    runs-on: ubuntu-latest
    outputs:
      should-update: ${{ steps.check.outputs.should-update }}
    steps:
      -
        id: check
        name: Check new release
        uses: vilgotf/container-update-action@main
        with:
          baseimage: library/python:3.8-slim
          image: vilgotf/red-discordbot:debian
          pypi: red-discordbot
  debian:
    needs: check_debian
    #if: needs.check_debian.outputs.should-update == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        base:
          - { tag: audio-debian, target: audio }
          - { tag: debian, target: audio }
          - { tag: full-debian, target: full }
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./Containerfile.debian
          target: ${{ matrix.base.target }}
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: vilgotf/red-discordbot:${{ matrix.base.tag }}
